class Solution {
       public int minOperations(int[] nums, int k) {
              Arrays.sort(nums);
                     List<Integer> orig = new ArrayList<>();
                            for (int num : nums) {
                                       if (num < k) {
                                                      orig.add(num);
                                                                 } else {
                                                                                break;
                                                                                           }
                                                                                                  }
                                                                                                         List<Integer> trans = new ArrayList<>();
                                                                                                                int cnt = 0, i = 0, j = 0;
                                                                                                                       while (i < orig.size() || j < trans.size()) {
                                                                                                                                  cnt++;
                                                                                                                                             int cand11 = getMin(i, orig), cand12 = getMin(j, trans), num1 = 0;
                                                                                                                                                        if (cand11 < cand12) {
                                                                                                                                                                       num1 = cand11;
                                                                                                                                                                                      i++;
                                                                                                                                                                                                 } else {
                                                                                                                                                                                                                num1 = cand12;
                                                                                                                                                                                                                               j++;
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                     int cand21 = getMin(i, orig), cand22 = getMin(j, trans), num2 = 0;
                                                                                                                                                                                                                                                                if (cand21 < cand22) {
                                                                                                                                                                                                                                                                               num2 = cand21;
                                                                                                                                                                                                                                                                                              i++;
                                                                                                                                                                                                                                                                                                         } else {
                                                                                                                                                                                                                                                                                                                        num2 = cand22;
                                                                                                                                                                                                                                                                                                                                       j++;
                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                             if (num2 == Integer.MAX_VALUE) {
                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                  long newNum = 2l * num1 + num2;
                                                                                                                                                                                                                                                                                                                                                                                                             if (newNum < k) {
                                                                                                                                                                                                                                                                                                                                                                                                                            trans.add((int) newNum);
                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                     return cnt;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                           private int getMin(int idx, List<Integer> arr) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (idx < arr.size()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return arr.get(idx);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return Integer.MAX_VALUE;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

